name: xcvbnm
version: 0.3.5
author: Werner Gaisbauer @ Exit Live, alex@tekartik.com
description: This is intended as a Dart port of zxcvbn (see https://github.com/dropbox/zxcvbn).
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  dart_to_js_script_rewriter: any
dev_dependencies:
  test: ^0.12.0
  browser: any
transformers:
- dart_to_js_script_rewriter
